version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - ls -la
      - cd lambda/averagetempLambda
      - zip -r ../averagetempLambda.0.0.5.zip .
      - cd ../currentTemperatureLambda
      - zip ../currenttemperatureLambda.1.0.0.zip index.js
artifacts:
  files:
    - cloudformation/*
    - lambda/*
    - mainCloudformation.json
    - stagingConfiguration.json
    - productionConfiguration.json